version: '3.8'

services:
  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ports:
      - "9200:9200"
      - "9600:9600"
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - lsm-network
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8g
        reservations:
          cpus: "2"
          memory: 4g

  opensearch-dashboard-node:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboard-node
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=https://opensearch-node:9200  # This is crucial for connecting to the OpenSearch node
    depends_on:
      - opensearch-node
    networks:
      - lsm-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2g
        reservations:
          cpus: "0.25"
          memory: 250M
  
  middleware:
    build: ./middleware
    container_name: middleware-node
    environment:
      - discovery.type=single-node
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLLAMA_PORT=${OLLAMA_PORT}
      - OS_HOST=${OS_HOST}
      - MDW_PORT=${MDW_PORT}
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ports:
      - "2002:2002"
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - lsm-network
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2g
        reservations:
          cpus: "0.25"
          memory: 250M

  ollama-node:
    # image: ollama/ollama:latest
    build: ./ollama
    container_name: ollama-node
    ports:
      - "11434:11434"
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - lsm-network
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 20g
        reservations:
          cpus: "4"
          memory: 8g
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  lsm-network:
