### GETS
GET http://localhost:3000/api/apps/

###
GET http://localhost:3000/api/apps/example

###
GET http://localhost:3000/api/apps/test2


### CREATE APP
POST http://localhost:3000/api/apps/
Content-Type: application/json

{
    "name": "test"
}

### 
POST http://localhost:3000/api/apps/
Content-Type: application/json

{
    "name": "test2",
    "terms": [
        {
        "model": "llama3",
        "role": "admin",
        "content": "admin content"
        },
        {
        "role": "user",
        "content": "user content"
        }
    ],
    "conclusions": [
        {
        "role": "admin",
        "content": "admin content"
        },
        {
        "model": "llama3",
        "role": "user",
        "content": "user content"
        }
    ]
}

### Update apps
PATCH http://localhost:3000/api/apps/
Content-Type: application/json

{
    "orig_name": "test",
    "name": "test5",
    "terms": [
        {
        "model": "llama3",
        "role": "admin",
        "content": "admin content"
        },
        {
        "role": "user",
        "content": "user content"
        }
    ],
    "conclusions": [
        {
        "role": "admin",
        "content": "admin content"
        },
        {
        "model": "llama3",
        "role": "user",
        "content": "user content"
        }
    ]
}

### DELETE APPS
DELETE http://localhost:3000/api/apps/test

### 
DELETE http://localhost:3000/api/apps/test2