###
POST http://localhost:3001/ask
Content-Type: application/json

{
    "message" : "Name me the planets of the solar system"
}

###
POST http://localhost:3001/ask
Content-Type: application/json

{
    "message" : "Given the statement to capture the terms: 'I have the flu and a very bad back pain.' Identify and list the medical terms present without providing any additional information or definitions."
}


###
POST http://localhost:3001/ask
Content-Type: application/json

{
    "message" : "Given the text: 'Yesterday, I started feeling a sore throat and a fever. This morning, my symptoms included a runny nose and a cough.' Identify and list the medical terms present without providing any additional information or definitions."
}

###
POST http://localhost:3001/get_terms
Content-Type: application/json

{
    "message" : "Given the text: 'Yesterday, I started feeling a sore throat and a fever. This morning, my symptoms included a runny nose and a cough.' Identify and list the medical terms present without providing any additional information or definitions."
}

###
POST http://localhost:3001/get_terms
Content-Type: application/json

{
    "message" : "Given the text, name the illegal things: During a routine traffic stop, a vehicle was found to be transporting a significant quantity of substances believed to be narcotics. The driver was detained for possession with intent to distribute, as well as for driving under the influence (DUI). The substances were sent for lab analysis to confirm their composition. Additionally, the vehicle's registration was expired, and there was an open container of alcohol in the car."
}