###
POST http://localhost:3000/api/ask/
Content-Type: application/json

{
    "message": "What means Luna?"
}
###


###
POST http://localhost:3000/api/ask/
Content-Type: application/json

{
    "message": "To the following question, you will answer with the medical terms of the situation of the patient. For example, Q: I have a heache.\nA: headche.\nNow you, Q:I have a lot of pain in my head A:"
}
###