###
POST http://localhost:3000/api/ask/
Content-Type: application/json

{
    "message": "Yesterday, I started feeling a sore throat and a fever. This morning, my symptoms included a runny nose and a cough."
}


###
POST http://localhost:3000/api/ask/
Content-Type: application/json

{
    "message": "Last week, after trying a new food, I experienced itching, redness on my skin, and slight swelling around my lips. I also noticed hives appearing on my arms."
}


###
POST http://localhost:3000/api/ask/
Content-Type: application/json

{
    "message": "Given the text, Identify and list the medical terms present without providing any additional information or definitions: For several weeks now, I've been having trouble falling asleep. Even when I do, I wake up multiple times during the night. In the morning, I don't feel rested and struggle with daytime tiredness."
}


###
POST http://localhost:3000/api/ask/
Content-Type: application/json

{
    "message": "Given the text, Identify and list the medical terms present without providing any additional information or definitions: I have a sore throat"
}